[package]
name = "devsync"
version = "0.1.0"
description = "DevSync desktop app"
authors = ["DevSync"]
edition = "2021"

[lib]
name = "devsync_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
tauri = { version = "2.9.5", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
